import {
  AmenityAppliances,
  AmenityBlind,
  AmenityConditioning,
  AmenityDoublePaneWindows,
  AmenityEntranceDoor,
  AmenityFlooring,
  AmenityFurnished,
  AmenityGeneral,
  AmenityHeating,
  AmenityHotelServices,
  AmenityInteriorCondition,
  AmenityInteriorDoors,
  AmenityInternet,
  AmenityKitchen,
  AmenityMeters,
  AmenityMiscellaneous,
  AmenityRealEstateFacilities,
  AmenityRealEstateServices,
  AmenityShutters,
  AmenityStreetDevelopment,
  AmenityThermalInsulation,
  AmenityUtilitySpaces,
  AmenityWalls,
  BuildingStructure,
  BuildingType,
  Comfort,
  CompartmentalizationType,
  ConstructionPeriod,
  ConstructionStage,
  Destination,
  EnergyCertificationClass,
  HousingType,
} from "@/common/enums/imobiliare/imobiliare.enums";
import { ApartmentSellPayload } from "@/common/interfaces/imobiliare/imobiliare.interface";

export const APARTMENT_SELL_MOCK: ApartmentSellPayload = {
  value: {
    custom_reference: "test103",
    agents: [121],
    category_api: 102,
    project_id: null,
    project_url: "https://www.imobiliare.ro/ansamblu-rezidential/cosmopolis-nord",
    location_id: 30024,
    street_number: "10",
    street_name: "Aradului",
    block: "B23",
    entrance: "A",
    apartment_number: "11",
    map_marker_type: "pin",
    latitude: 45.79137086692758,
    longitude: 21.209369144540034,
    price: 100001,
    price_currency: "EUR",
    title: "titlu properitate maxim 80 caractere",
    description:
      "descriere properitate minim 80 caractere descriere properitate minim 80 caractere",
    data_properties: {
      bathroom_count: "1",
      floor_number: "1",
      number_of_floors: "4",
      bedroom_count: 3,
      year_built: "1980",
      destination: [
        Destination.RESIDENTIAL,
        Destination.COMMERCIAL,
        Destination.OFFICE_SPACE,
        Destination.VACATION,
      ],
      amenities_general: [
        AmenityGeneral.CATV,
        AmenityGeneral.GAS,
        AmenityGeneral.INTERNATIONAL_PHONE,
        AmenityGeneral.PHONE,
        AmenityGeneral.POWER,
        AmenityGeneral.SEWERAGE,
        AmenityGeneral.WATER,
      ],
      amenities_heating: [
        AmenityHeating.OTHER_ELECTRICAL_METHODS,
        AmenityHeating.RADIATORS,
        AmenityHeating.CENTRAL_BUILDING,
        AmenityHeating.CENTRAL_HEATING,
        AmenityHeating.GAS_CONVECTOR,
        AmenityHeating.UNDERFLOOR_HEATING,
        AmenityHeating.INFRARED_PANELS,
        AmenityHeating.DISTRICT_HEATING,
        AmenityHeating.TILE_STOVE,
      ],
      amenities_conditioning: [
        AmenityConditioning.AIR_CONDITIONING,
        AmenityConditioning.AIR_HEATERS,
        AmenityConditioning.FAN_COIL_UNITS,
      ],
      amenities_internet: [
        AmenityInternet.CABLE,
        AmenityInternet.OPTIC_FIBRE,
        AmenityInternet.WIRELESS,
        AmenityInternet.DIAL_UP,
      ],
      amenities_double_pane_windows: [
        AmenityDoublePaneWindows.PVC,
        AmenityDoublePaneWindows.WOOD,
        AmenityDoublePaneWindows.ALUMINUM,
      ],
      amenities_interior_condition: [
        AmenityInteriorCondition.RENEWED,
        AmenityInteriorCondition.GOOD_CONDITION,
        AmenityInteriorCondition.NEEDS_RENOVATION,
      ],
      amenities_interior_doors: [
        AmenityInteriorDoors.CELL_PHONES,
        AmenityInteriorDoors.WOOD,
        AmenityInteriorDoors.PANEL,
        AmenityInteriorDoors.PVC,
        AmenityInteriorDoors.GLASS,
      ],
      amenities_entrance_door: [
        AmenityEntranceDoor.PAL,
        AmenityEntranceDoor.WOOD,
        AmenityEntranceDoor.METAL,
        AmenityEntranceDoor.PVC,
        AmenityEntranceDoor.PARQUET,
      ],
      amenities_shutters: [AmenityShutters.PVC, AmenityShutters.WOOD, AmenityShutters.ALUMINUM],
      amenities_blind: [AmenityBlind.HORIZONTAL, AmenityBlind.VERTICAL],
      amenities_thermal_insulation: [
        AmenityThermalInsulation.EXTERIOR,
        AmenityThermalInsulation.INTERIOR,
      ],
      amenities_flooring: [
        AmenityFlooring.FLOOR,
        AmenityFlooring.FLOOR_TILES,
        AmenityFlooring.MARBLE,
        AmenityFlooring.CARPET,
        AmenityFlooring.PARQUET,
        AmenityFlooring.LINOLEUM,
      ],
      amenities_walls: [
        AmenityWalls.FAIENCE,
        AmenityWalls.WASHABLE_PAINT,
        AmenityWalls.VINAROM,
        AmenityWalls.LIME,
        AmenityWalls.DIRT_CLAY,
        AmenityWalls.PANELING,
        AmenityWalls.WALLPAPER,
      ],
      amenities_utility_spaces: [
        AmenityUtilitySpaces.TERRACE,
        AmenityUtilitySpaces.SERVICE_TOILET,
        AmenityUtilitySpaces.BASEMENT_STORAGE,
        AmenityUtilitySpaces.CLOSET,
      ],
      amenities_kitchen: [AmenityKitchen.EQUIPPED, AmenityKitchen.FURNISHED],
      amenities_furnished: [AmenityFurnished.COMPLETE, AmenityFurnished.LUXURY],
      amenities_meters: [
        AmenityMeters.GAS_METER,
        AmenityMeters.WATER_METER,
        AmenityMeters.HEAT_METER,
      ],
      amenities_real_estate_facilities: [
        AmenityRealEstateFacilities.LEISURE_AREAS,
        AmenityRealEstateFacilities.GARDEN,
        AmenityRealEstateFacilities.DRYER,
        AmenityRealEstateFacilities.OUTDOOR_POOL,
        AmenityRealEstateFacilities.INDOOR_POOL,
        AmenityRealEstateFacilities.ELEVATOR,
        AmenityRealEstateFacilities.INTERCOM,
        AmenityRealEstateFacilities.ROOF,
        AmenityRealEstateFacilities.YARD,
        AmenityRealEstateFacilities.COMMON_YARD,
        AmenityRealEstateFacilities.VIDEO_INTERCOM,
        AmenityRealEstateFacilities.SAUNA,
        AmenityRealEstateFacilities.SPA,
      ],
      amenities_appliances: [
        AmenityAppliances.DVD,
        AmenityAppliances.IRON,
        AmenityAppliances.COFFEE_MAKER,
        AmenityAppliances.HAIR_DRYER,
        AmenityAppliances.TOASTER,
        AmenityAppliances.HI_FI,
        AmenityAppliances.WASHING_MACHINE,
        AmenityAppliances.SANDWICH_MAKER,
        AmenityAppliances.FRIDGE,
        AmenityAppliances.MICROWAVE,
        AmenityAppliances.STOVE,
        AmenityAppliances.HOOD,
        AmenityAppliances.DISHWASHER,
        AmenityAppliances.KITCHEN_ROBOT,
        AmenityAppliances.VACUUM_CLEANER,
        AmenityAppliances.TV,
      ],
      amenities_miscellaneous: [
        AmenityMiscellaneous.FIREPLACE,
        AmenityMiscellaneous.INTERIOR_STAIRCASE,
        AmenityMiscellaneous.JACUZZI,
        AmenityMiscellaneous.SMOKE_SENSOR,
        AmenityMiscellaneous.ALARM_SYSTEM,
        AmenityMiscellaneous.GARAGE_DOOR_REMOTE_CONTROL,
        AmenityMiscellaneous.CAR_DOOR_REMOTE_CONTROL,
      ],
      amenities_real_estate_services: [
        AmenityRealEstateServices.ADMINISTRATION,
        AmenityRealEstateServices.HOUSEKEEPING,
        AmenityRealEstateServices.SECURITY,
        AmenityRealEstateServices.VIDEO_SURVEILLANCE,
      ],
      amenities_hotel_services: [
        AmenityHotelServices.CLEANING,
        AmenityHotelServices.BED_SHEETS,
        AmenityHotelServices.TOWELS,
        AmenityHotelServices.AIRPORT_TRANSFER_STATION,
        AmenityHotelServices.CITY_TOUR,
      ],
      amenities_street_development: [
        AmenityStreetDevelopment.ASPHALT,
        AmenityStreetDevelopment.CONCRETE,
        AmenityStreetDevelopment.PAVING,
        AmenityStreetDevelopment.DIRT_ROAD,
        AmenityStreetDevelopment.UNDEVELOPED,
        AmenityStreetDevelopment.STREET_LIGHTING,
        AmenityStreetDevelopment.PUBLIC_TRANSPORTATION,
      ],
      energy_certification_class: EnergyCertificationClass.A,
      energy_primary_consumption: "51",
      energy_co2_emission_index: "52",
      energy_consumption_renewable_resources: "53",
      expired_at: "2025-07-31",
      exclusive: true,
      exclusivity_valid_from: "2025-07-16 09:51:00",
      exclusivity_valid_to: "2025-07-19 09:51:00",
      open_house_start_time: "08:00",
      expired_at_time: "05:00",
      open_house_stop_time: "17:00",
      open_house_address: "adresa open house",
      open_house_date: "2025-07-19",
      housing_type: HousingType.APARTMENT,
      building_type: BuildingType.APARTMENT_BUILDING,
      other_price_details: "alte detalii pret",
      other_private_details: "Alte detalii private 21k caractere",
      safety_measures: null,
      neighborhood: "vecinatati 21k caractere",
      vices: "vicii 21k caractere",
      property_availability: "Disponibilitate proprietate 200 caractere",
      balcony_count: "1",
      closed_balcony_count: "1",
      kitchen_count: "1",
      garage_count: "1",
      parking_space_count: "1",
      building_structure: BuildingStructure.BRICK,
      video_viewing: true,
      pets_allowed: true,
      un_inhabited_property: null,
      other_details: "Alte detalii 21k caractere",
      compartmentalization_type: CompartmentalizationType.DETACHED,
      comfort: Comfort.COMFORT_1,
      construction_period: ConstructionPeriod.BETWEEN_1978_1990,
      basement: true,
      semi_basement: true,
      ground_floor: true,
      attic: true,
      usable_surface: "100",
      built_area: "102",
      total_usable_surface: "101",
      collaboration: true,
      collaboration_commission_percentage: 10,
      collaboration_commission_value: 1500,
      seller_commission: "9",
      commission_zero: false,
      buyer_commission: "8",
      construction_stage: ConstructionStage.COMPLETED,
      poa: false,
      hide_exact_location: false,
      other_area_details: "",
      stair: "",
      block_number: "",
      executive_file_number: "",
      price_no_vat: false,
    },
  },
};
