import {
  AmenityGeneral,
  BuildingCondition,
  BuildingType,
  ConstructionStage,
  EnergyCertificationClass,
} from "@/common/enums/imobiliare/imobiliare.enums";
import { CommercialSpaceRentPayload } from "@/common/interfaces/imobiliare/imobiliare.interface";

export const COMMERCIAL_SPACE_RENT_MOCK: CommercialSpaceRentPayload = {
  value: {
    custom_reference: "test117",
    category_api: 215,
    project_id: null,
    location_id: 30024,
    street_number: "10",
    street_name: "Aradului",
    block: null,
    entrance: null,
    apartment_number: null,
    map_marker_type: "pin",
    latitude: 45.792716809776124,
    longitude: 21.207824955464545,
    price: 0,
    price_currency: "EUR",
    agents: [121],
    title: "titlu properitate maxim 80 caractere",
    description:
      "descriere properitate minim 80 caractere descriere properitate minim 80 caractere",

    data_properties: {
      hide_exact_location: null,
      price_per_available_area: "100",

      exclusive: true,
      exclusivity_valid_from: "2025-07-16 09:26:00",
      exclusivity_valid_to: "2025-07-26 09:26:00",
      collaboration: true,
      collaboration_commission_percentage: 10,
      collaboration_commission_value: 1500,
      seller_commission: "8",
      buyer_commission: "9",
      commission_zero: false,

      other_price_details: "",
      price_no_vat: false,
      poa: false,

      auction_execution_stage: "amiable-sale",
      priority: null,
      hide_price: false,

      number_of_floors: "3",
      number_of_sub_terrean_floors: "2",
      year_built: "2008",
      energy_certification_class: EnergyCertificationClass.B,
      property_name: "test nume proprietate",
      energy_primary_consumption: "100",
      energy_co2_emission_index: "101",
      energy_consumption_renewable_resources: "102",

      mezzanine: true,
      building_occupancy_degree: "10",
      building_condition: BuildingCondition.UPGRADED,
      building_type: BuildingType.MALL,
      commercial_space_type: null,
      sale_price: null,

      other_private_details: "Alte detalii private 21k caractere",
      neighborhood: "vecinatati 21k caractere",
      parking_space_count: "8",
      compartmentalization_possible: null,
      video_viewing: true,
      entresol: null,
      semi_basement: true,
      ground_floor: true,
      attic: true,
      terrace: true,

      total_usable_surface: "50",
      height_condition: null,
      construction_stage: ConstructionStage.EXIST,
      land_area: "1500",
      year_of_modernization: "2015",

      partitioning_possible: true,
      location_is_verified: null,

      amenities_general: [
        AmenityGeneral.AIR_CONDITIONING,
        AmenityGeneral.GAS,
        AmenityGeneral.HEATING_SYSTEM,
        AmenityGeneral.POWER,
        AmenityGeneral.SEWERAGE,
        AmenityGeneral.WATER,
      ],
    },

    space_props: [
      {
        expired_at: "2025-07-24",
        expired_at_time: "00:30",
        space_description: "spatiu 1 descriere",
        space_name: "spatiu 1 nume",
        renting_commission_percentage: "9",
        space_availability: "immediate",
        contract_expiration_date: null,
        availability_date: null,
        available_area: "100",
        floor_number: "1",
        minimum_divisible_area: "100",
        id: null,
        maintenance_cost_added: true,
        price: 10000,
        price_per_available_area: "100",
        price_currency: "EUR",
        space_height: "9",
        showcase: true,
        parking_available: true,
      },
      {
        expired_at: "2025-07-24",
        expired_at_time: "00:30",
        space_description: "spatiu 2 descriere",
        space_name: "spatiu 2 nume",
        renting_commission_percentage: "9",
        space_availability: "immediate",
        contract_expiration_date: null,
        availability_date: null,
        available_area: "105",
        floor_number: "1",
        minimum_divisible_area: "100",
        id: null,
        maintenance_cost_added: true,
        price: 8400,
        price_per_available_area: "80",
        price_currency: "EUR",
        space_height: "9",
        showcase: true,
        parking_available: true,
      },
    ],
  },
};
