import {
  ConstructionPeriod,
  ConstructionStage,
  Destination,
  HousingType,
  RoofType,
} from "@/common/enums/imobiliare/imobiliare.enums";
import { HouseRentPayload } from "@/common/interfaces/imobiliare/imobiliare.interface";

export const HOUSE_RENT_MOCK: HouseRentPayload = {
  value: {
    custom_reference: "test107",
    category_api: 206,
    project_id: null,
    location_id: 30024,
    street_number: "10",
    street_name: "Aradului",
    block: null,
    entrance: null,
    apartment_number: null,
    map_marker_type: "pin",
    latitude: 45.79092174442872,
    longitude: 21.209712297667945,
    price: 500,
    price_currency: "EUR",
    agents: [121],
    title: "titlu proprietate maxim 80 caractere",
    description:
      "descriere proprietate minim 80 caractere descriere proprietate minim 80 caractere",
    data_properties: {
      poa: "false,",
      year_built: "1980",
      exclusive: true,
      exclusivity_valid_from: "2025-07-16 01:34:00",
      exclusivity_valid_to: "2025-07-26 01:35:00",
      open_house_start_time: "08:00",
      open_house_stop_time: "17:00",
      open_house_address: "adresa open house",
      open_house_date: "2025-07-18",
      other_price_details: "alte detalii pret",
      price_no_vat: false,
      housing_type: HousingType.OTHERS,
      collaboration: true,
      collaboration_commission_percentage: 10,
      collaboration_commission_value: 1500,
      seller_commission: "8",
      commission_zero: false,
      buyer_commission: "9",
      bedroom_count: "1",
      property_type: null,
      bathroom_count: "1",
      terrace_count: "1",
      terrace_area: "20",
      number_of_floors: "2",
      video_viewing: true,
      pets_allowed: true,
      un_inhabited_property: null,
      other_details: "alte detalii 21k caractere",
      roof_type: RoofType.BOARD,
      construction_period: ConstructionPeriod.BETWEEN_1978_1990,
      basement: true,
      semi_basement: true,
      ground_floor: true,
      attic: true,
      usable_surface: "100",
      built_area: "102",
      developed_area: "101",
      height_condition: null,
      construction_stage: ConstructionStage.TO_GRAY,
      land_area: "500",
      priority: null,
      destination: [
        Destination.RESIDENTIAL,
        Destination.COMMERCIAL,
        Destination.OFFICE_SPACE,
        Destination.VACATION,
      ],
    },
  },
};
